### ISSUE TITLE
Jisho-OJAD chrome extension

### ISSUE THREAD

**Issue by kandyman2017** [olety/japanese-pitch-accent-resources#1]
I'm not sure if this is such a good resource - it doesn't work for me. There's a bad review of it on the store, and I've heard from others that they couldn't get it to work properly either. If it works well for you, then I guess it must be an issue with my setup.

**Comment by olety** [comment]
Hi, the extension works for me, even though it takes some time to load. I'll try installing it on a fresh VM and see whether it'll work there :) 

<img width="1099" alt="2018-03-30 11 54 49" src="https://user-images.githubusercontent.com/2990542/38131857-4c58a234-3411-11e8-9771-cb4aafea9fe8.png">

**Comment by olety** [comment]
[I've tested it and it works just fine.](https://www.youtube.com/watch?v=W-LgqUI8ehg) 

You might encounter some problems when searching for harder words because they use [this dictionary/database](http://www.gavo.t.u-tokyo.ac.jp/ojad/) which should be 99.9% correct but doesn't cover every word/phrase and not the [machine learning version](http://www.gavo.t.u-tokyo.ac.jp/ojad/eng/phrasing/index) which can be hit or miss sometimes, but should be able to handle any word you throw at it. 

If you can understand J-J dictionary definitions, I'd recommend just getting a hold of some EPWING dictionaries and using either [qolibri](http://qolibri.osdn.jp/) or [GoldenDict](http://goldendict.org/) to look stuff up in them. Since you can look a word up in multiple dictionaries at the same time, you can read a definition from one dictionary and look up the pitch accent in a different one. (IIRC, there should be some E-J EPWINGs) 

<img width="1920" alt="2018-03-30 0 46 18" src="https://user-images.githubusercontent.com/2990542/38133567-71739504-3418-11e8-8f7a-a9f72a6169e9.png">

I guess I'll add those dictionary viewers under "Other", since they're quite useful. 😄

**Comment by olety** [comment]
Sorry, I was just playing around with issues since I'm not used to having them in a public project yet :D 
Please close it if you feel like it's solved.

**Comment by kandyman2017** [comment]
I reinstalled it and tried again but it doesn't work for me. It's obviously an issue with my system. 

As for EPWING dictionaries, I have tried installing one but I am not good with technical stuff at all, so I didn't have any success adding dictionaries to quolibri.

**Comment by kandyman2017** [comment]
Which dictionaries do you have? I could only Edict, which doesn't show pitch accent.

**Comment by kandyman2017** [comment]
I could use some help with qolibri too. Can I contact you directly?

**Comment by olety** [comment]
You can find instructions on how to get most of the dictionaries that I have in the #resourses channel of [AJATT](https://www.patreon.com/mattvsjapan/posts) discord, but you do have to donate at least $1 to be able to read the messages ($10 is required to post). 
Amazon also has some of them available on either CD drives/as downloadable files. [新明解国語辞典](https://www.amazon.co.jp/%E3%83%AD%E3%82%B4%E3%83%B4%E3%82%A3%E3%82%B9%E3%82%BF-%E6%96%B0%E6%98%8E%E8%A7%A3%E5%9B%BD%E8%AA%9E%E8%BE%9E%E5%85%B8-%E7%AC%AC%E4%B8%83%E7%89%88/dp/B00B8CR9OO)

Sure, shoot me up an email olkyrylchuk@gmail.com :)
